
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.1';

const supabaseUrl = Deno.env.get('SUPABASE_URL');
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
const googleSheetsWebhook = Deno.env.get('HEYGEN_GOOGLE_SHEETS_WEBHOOK');

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface HeyGenRequest {
  instruction: string;
  imageUrl?: string;
  productInfo?: {
    name: string;
    description: string;
  };
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { instruction, imageUrl, productInfo }: HeyGenRequest = await req.json();

    if (!googleSheetsWebhook) {
      throw new Error('Google Sheets webhook URL not configured. Please add HEYGEN_GOOGLE_SHEETS_WEBHOOK to Supabase secrets.');
    }

    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Supabase configuration missing');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log('Starting HeyGen video generation via Google Sheets + Zapier');

    // Prepare data for Google Sheets
    const sheetData = {
      timestamp: new Date().toISOString(),
      instruction: instruction,
      product_name: productInfo?.name || "Premium Wireless Headphones",
      product_description: productInfo?.description || "High-quality audio experience with noise cancellation",
      image_url: imageUrl || "",
      status: "pending",
      source: "feedgenerator_app"
    };

    console.log('Sending data to Google Sheets:', sheetData);

    // Post to Google Sheets via webhook/Zapier
    const response = await fetch(googleSheetsWebhook, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(sheetData),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Failed to post to Google Sheets: ${response.status} - ${errorText}`);
    }

    // Generate a placeholder video URL for immediate feedback
    // In reality, the video will be generated by HeyGen via Zapier
    const placeholderVideoUrl = 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4';
    
    // Store in database with pending status
    const { data: asset, error: dbError } = await supabase
      .from('generated_assets')
      .insert({
        channel: 'youtube',
        format: 'mp4',
        source_system: 'heygen_zapier',
        asset_type: 'video',
        url: placeholderVideoUrl,
        instruction: instruction,
        approved: false
      })
      .select()
      .single();

    if (dbError) {
      throw new Error(`Database error: ${dbError.message}`);
    }

    console.log('HeyGen video generation request sent to Google Sheets successfully');

    return new Response(JSON.stringify({ 
      success: true, 
      asset_url: placeholderVideoUrl,
      asset_id: asset.id,
      type: 'video',
      message: 'Video generation request sent to Google Sheets. HeyGen will process via Zapier automation.',
      sheets_data: sheetData
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('Error in heygen-generate function:', error);
    return new Response(JSON.stringify({ 
      success: false, 
      error: error.message 
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
