// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://speqcclarritenwiyrzl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZXFjY2xhcnJpdGVud2l5cnpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTM1NjIsImV4cCI6MjA2NjQyOTU2Mn0.xzC8HwByqv6oDng_nKeCtZfrpDgE4fOxz5QUQLVME5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);